<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Windows\HomeMediaRemote.Audio.Windows\HomeMediaRemote.Audio.Windows.csproj" />
    <ProjectReference Include="..\Windows\HomeMediaRemote.Media.Windows\HomeMediaRemote.Media.Windows.csproj" />
    <ProjectReference Include="..\Windows\HomeMediaRemote.Pc.Windows\HomeMediaRemote.Pc.Windows.csproj" />
  </ItemGroup>

</Project>
