<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\Mic\" />
    <Folder Include="Commands\Pc\" />
    <Folder Include="Commands\Screen\" />
    <Folder Include="Commands\Sound\" />
  </ItemGroup>

</Project>
